### ISSUE TITLE
Search for secrets in Ingresses

### ISSUE THREAD

**Issue by Pscheidl** [Pscheidl/kubexplorer#1]
Ingresses might link to secret maps and configs as well, e.g. in the `tls` section. 

```yaml
--- 
apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
name: tls-example-ingress
spec: 
rules: 
- 
host: mydomain.com
http: 
paths: 
- 
backend: 
serviceName: my-service
servicePort: 80
path: /
tls: 
- 
hosts: 
- mydomain.com
secretName: my-tls-secret
```
